### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by rashidmvk**
A clone of the New York Times website:
This a collaborative practical project for educational purpose built by Rashid. The basic features used Flexbox, Grid, Floats, Positioning and box model.

### CODE REVIEW

**Comment by bertil291utn** [comment]
**Status:** Changes requested 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

But in order to accomplish as the actual page, you required to do these changes, listed below: 

#### Linter errors

- [ ] Your forgot add the [linters folder](https://github.com/microverseinc/linters-config/tree/master/html-css) correctly. Please add a correct file and check if you don't have linter errors
  - You have `.github/linter.yml` should be `.github/workflows/linter.yml`

#### General review

**Navigation Bar**

- [ ] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). You have your logo with no link 

image

**Main content**

- [ ] Add `overflow-x:hidden;` to body property to your CSS  file, to avoid horizontal scrolling

- [ ] It should contains centered text and images ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

image

**Bottom part**


- [ ] It should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

image

- [ ] It should contain links to more popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

image

<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Comment by rashidmvk** [comment]
Corrected the above suggested changes and resubmitted it. We look forward to hear from you soon.

**Comment by digitekh2i** [comment]
Following all the explanations for the mentioned concerns:


1. Thanks for your feedback.  We have actually fixed the linter errors before this code review when  the first TSE had mentioned about it .Kindly have a re-check on this. 

2. We re-checked our project through our live demo link  and functionalities are intact. The attached file below is the screenshot of our project from our live demo link. as you have told us to take the screenshot of the same.

diagram-live 

We look forward to hearing you soon.

**Comment by bertil291utn** [comment]
**Status:** Changes requested 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

Your page looks amazing it's almost a clone I see you put all your effort, however, you need to work on little details. 

- [ ] Remove or add to [.gitignore](https://www.atlassian.com/git/tutorials/saving-changes/gitignore) file  `.vscode/settings.json` directory , because is getting errors  

image

- [ ] Try to be the same as the original web page. Use grid property for this section

| ORIGINAL WEB PAGE                                            | YOURS                                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| image | image |

- [ ] Also the same section should be behind the navbar, take in mind also this.

  image

- [ ] **More in the space** section should be aligned to the center.
- [ ] First three articles have 3 times width than the last (Most popular) section 

| ORIGINAL WEB PAGE                                            | YOURS                                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| image | image |


##### Summary

Be careful the most of your sections should be aligned to the center

Use grid property to achieve all where you have tables and squares elements, it's been easier  



<hr>

Guys work in the requested changes above and request code for another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Comment by digitekh2i** [comment]
Thank you for all your feedback!
we have made all the necessary changes.

**Comment by digitekh2i** [comment]
One again! 
thank you for your feed back and directives.
Kindly review again.

**Comment by digitekh2i** [comment]
We Thank you all for the series code reviews.
I believe we're good to go now...
looking forward to your feedback

**Pull request merged**
